### ISSUE TITLE
Menu Items should respond to both "Enter" and "Spacebar"

### ISSUE THREAD

**Issue by malcalevak** [CodyHouse/cd-lightbox-changelog#2]
role="menuitem" elements should respond to both "Enter" and "Spacebar"

For reference:
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/menuitem_role

**Comment by claudia-romano** [comment]
Thanks for the heads-up! We have updated the component:
https://codyhouse.co/ds/components/app/lightbox
